[platformio]
default_envs = uno_official

; ---------- Arduino Uno R3 (official) ----------
[env:uno_official]
platform = atmelavr@5.1.0
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
  waspinator/AccelStepper@1.64
  bogde/HX711@^0.7.4
build_flags =
  -D BOARD_OFFICIAL_UNO
  -Os
  -ffunction-sections
  -fdata-sections

; ---------- Arduino Uno (SANEsmart clone) ----------
[env:uno_sanesmart]
platform = atmelavr@5.1.0
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
  waspinator/AccelStepper@1.64
  bogde/HX711@^0.7.4
build_flags =
  -D BOARD_SANE_UNO
  -Os
  -ffunction-sections
  -fdata-sections
